### ISSUE TITLE
Grid closes immediately when using -Gridview parameter

### ISSUE THREAD

**Issue by brandroidian** [matbe/PowerShell#1]
At the end of your Out-Gridview line, add a -Wait parameter

Read-CMLogfile -path $path |Where-Object {$_.Type -ge ([LogType]::($LogLevel).value__)} |Sort-Object DateTime | Out-GridView -Title "Powershell Logviewer by Mattias Benninge" -Wait

Otherwise, the grid opens for a brief second and then closes before it can be read.

**Comment by matbe** [comment]
I usually use it from within PowerShell ISE and that doesn't seem to be a problem then, but thanks for letting me know! I have added it to the script now.
