### ISSUE TITLE
Date/Time column is blank

### ISSUE THREAD

**Issue by ricofox959** [matbe/PowerShell#2]
On line 126 where it formats the PSObject, the time conversion seams to not be populating the datetime column.

**Comment by matbe** [comment]
I'm guessing its the Read-CMLog.ps1 script you are reporting a bug on?
It works here so need some more input to be able to be troubleshoot.
Could you provide a sample of a log that doesn't work (that works with cmtrace)?

Also what OS/locale/date format/powershell version and so on are you using?

**Comment by ricofox959** [comment]
Sorry, yes, its the Read-CMLog, I uploaded a sample of the log file that I was using.
[smsts.log](https://github.com/matbe/PowerShell/files/2457052/smsts.log)
souce log timezone is Eastern, same was true when looking at my own SMSTS.log my machine is Central Time zone.
SCCM 1806
Machine machine: Windows 10 1803 x64 Ent (OS Build 17134.285)
PowerShell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  228

**Comment by matbe** [comment]
Ok I have found the bug and hopefully fixed it, please test.

**Comment by ricofox959** [comment]
That fixed it! Thanks. Great Script too. This will save me tons of time
