### ISSUE TITLE
Apply to Option Request

### ISSUE THREAD

**Issue by mitlyng** [matbe/PowerShell#3]
Hello,

In the next version would you please add the ApplyTo (-ApplyToSoftwareUpdateOnly) field?

Thank you!

**Comment by matbe** [comment]
Is this for the New-CMMaintenanceWindow.ps1 script?
I'll se what I can do!

**Comment by matbe** [comment]
Is it not already in the script?
.PARAMETER SWType

    Sets the type of Maintainence Windows, default is General. Valid values are General, Updates and OSD

Or is it some other/new feature you are missing? If so please attach a link to the documentation so I can investigate it.

**Comment by mitlyng** [comment]
May be confusion on my part but I did not see the option to -applytosoftwareupdateonly https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmmaintenancewindow?view=sccm-ps#-applytosoftwareupdateonly

Thank you.

**Comment by matbe** [comment]
I do not use the commandlet for my script since it is missing functions that I needed, mine are built on the WMI methods available. The parameter SWType in my script should do what you are asking for.

Let me know if it works and i will close this issue.

**Comment by matbe** [comment]
No feedback so closing issue.
