### ISSUE TITLE
Get-EdgeEnterpriseMSI doesn't handle multiple files + other bits

### ISSUE THREAD

**Issue by KarlGrindon** [matbe/PowerShell#5]
Hey,

I've used Get-EdgeEnterpriseMSI and love the functionality. However I looked at the script and found things that could be improved.

I've rewritten a good chunk of the script to do things such as:

- Script now handles multiple files (e.g. MacOS Edge files, multiple policy files)
- More parameter validation
- Error handling (replacing write-host -colour red + breaks with throws)
- Formatting improvements (my opinion)
- Remote URI validation
- bumped version

Could I be added as a collaborator to add my branch please?

Thanks!

Karl

**Comment by matbe** [comment]
Hi Karl,

Please make a pull request and I will review your changes.

Thanks!

**Comment by KarlGrindon** [comment]
Hi,

Done.

Thanks,
