### ISSUE TITLE
Test-Path Folder

### ISSUE THREAD

**Issue by Top-Goodman** [matbe/PowerShell#7]
Hello, In version 1.2, if the folder is not detected, the script just has throw. Yet when ran, the throw did not happen.
I ran with the below arguments. C:\Temp exists. At runtime, the MSEdge folder in Temp did not
-Channel "Beta" -Folder C:\Temp\MSEdge -Platform Windows -Architecture x64 -Force

If you would like, please feel free to use this to create the non-existent folders

# Desired path
[string]$Path=""
# Split path into each specified folder name
[array]$Array=$Path.split('\')
# Starting from full path, remove a subfolder until we find a path that exists
($Array.Length..0)|ForEach-Object {
   $newPath=[string]::Join("\",$Array[0..$_])
# Once we find the outter most existing path (lowest existing subdirectory), break the loop
if (test-Path $newPath) {
    $indexExists=$_
    break
}
}
# Another loop to begin creating the subfolders until we have the full path
(($indexExists+1)..($Array.Length-1))|ForEach-Object{
    # Path of the highest subfolder that does not yet exist
    $makePath=[string]::Join("\",$Array[0..$_])
    # Make the folder
New-Item -ItemType Directory -Path $makePath
}
# Test to see if path now exists
Test-path $Path

**Comment by matbe** [comment]
Will not fix, just make sure the path exist before running the script.
